module.exports = {
  purge: {
    content: ['./src/**/*.{js,jsx,ts,tsx}'],
    options: {
      safelist: ['w-button-sm'],
    },
  },
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'neutral': {
          '50': '#dadada',
          '500': '#4d4d4d',
          '600': '#353535',
          '700': '#363636',
          '900': '#262626',
          '900-60': 'rgba(25, 25, 25, 0.6)', // #191919 c opacity 60%
          '950': '#1e1e1e',
        },
        'gray': {
          300: '#D5D5D5',
          600: '#4D4D4D',
          800: '#1f2937',
        },
        'blue': {
          '700': '#4a88c7',
          '800': '#0543a7',
          '800-8': 'rgba(5, 67, 167, 0.08)', // #0543A7 с opacity 8%
          '900': '#0c2975',
        },
        'genom-menu-gray': '#D8DADD',
        'genom-bg-gray': '#FAFAFA',
        'genom-bg-gray2': '#F2F2F2',
        'genom-light-gray': '#D5D5D5',
        'genom-light-gray2': '#EAEAEA',
        'genom-rose': '#E11D48',
        'genom-gray': '#4D4D4D',
        'genom-gray2': '#AFB0B4',
        'genom-blue': '#125EB7',
        'genom-black': '#191919',
        'genom-overlay': '#757575',
        'genom-green': '#32C787',
        'genom-sky': '#408BFC',
        'button-active': '#EBECEF',
        'stack': 'rgba(25, 25, 25, 0.25)', // (#191919 c opacity 25%
        'faststart-start': '#87C0F4',
        'faststart-end': '#6E94CE',
      },
      spacing: {
        'left-menu': '48px',
        'left-menu2': '84px',
        'left-menu-offset': '32px',
        'top-menu': '48px',
        'right-menu': '348px',
        'card-tablesize': '752px',
        'card-super-small': '160px',
        'genom-11': '11px',
        'button-48': '48px',
        'button-sm': '22px',
        'genom-full': 'calc(100% - 48px)',
        'research-card-top': '-66px',
        'research-card-left': '-44px',
        'faststart-top': '-76px',
        'faststart-left': '-28px',
        'genom-browser': '65vh',
        'genom-deposit-filelist': '65vh',
        'genom-di': '70vh',
        'genom-work-space': '85vh',
        'force-full': '100% !important',
        'table-col-sm': '36px',
        'hide-scroll': '-40px',
      },
      maxWidth: {
        'left-menu': '48px',
        'top-menu': '48px',
        'card-big': '872px',
        'card-middle': '648px',
        'card-small': '424px',
        'card-super-small': '200px',
        'edit-col-1': '160px',
        'edit-col-2': '80px',
        'login-container': '500px',
        'search-col': '250px',
        'outer-table': 'calc(100vw - 48px - 32px - 48px)',
        'half': '50%',
        '1/4': '25%',
      },
      minWidth: {
        'left-menu': '48px',
        'right-menu': '300px',
        'table-col-1': '160px',
        'card-big': "calc(872px - theme('spacing.6') * 2)",
        'card-middle': "calc(648px - theme('spacing.6') * 2)",
        'card-small': "calc(424px - theme('spacing.6') * 2)",
        'card-super-small': '200px',
        'stack': '600px',
        'param-col-1': '128px',
        'edit-col-1': '160px',
        'edit-col-1-static': '250px',
        'edit-col-2': '80px',
        'time-col-1': '50px',
        'line': '1px',
        'statistic-dot': '12px',
        'statistic-table-header': '88px',
        'static-big': '900px',
      },
      width: {
        'card-middle': '648px',
        'genom-map': 'calc(100% - 50px)',
        'card-no-scroll': 'calc(100% - 24px)',
      },
      minHeight: {
        'calendar-item': '80px',
        'logo-icon': '48px',
        'menu-icon': '48px',
        'button-icon': '48px',
        '8': '1.5rem',
        '10': '2.5rem',
        'card-small': '248px',
        'card-super-small': '160px',
        'tile-view': '116px',
        'table-row-1': '48px',
        'button-icon-sm': '22px',
      },
      maxHeight: {
        'table-row-2': '20%',
        'screen': '100vh',
      },
      boxShadow: {
        'card': '0px 4px 16px rgba(77, 78, 80, 0.08)',
        'bar-select': '0px 0px 6px 1px rgba(18, 94, 183, 0.5)',
      },
      zIndex: {
        '-1': '-1',
      },
      gridTemplateColumns: {
        'form': 'minmax(128px, 40%) 60%',
        'form-sm': 'minmax(128px, 20%) 80%',
      },
    },
  },
  variants: {
    extend: {
      opacity: ['dark'],
      padding: ['first'],
      borderColor: ['dark'],
      borderWidth: ['dark'],
      backgroundColor: ['active', 'first'],
    },
  },
  plugins: [],
};
