version: '3'

services:
  
  client:
    build: 
      context: bert-search-app
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    build: 
      context: bert_flask_service
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - /home/dasha/docker-k8s-test/bert_flask_service/model_save_v2_10k_20e:/home/dasha/docker-k8s-test/bert_flask_service/model_save_v2_10k_20e
      - /home/dasha/datasets:/home/dasha/datasets
