apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels: 
    app: {{ .Values.labels }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: client-port
      port: {{ .Values.service.clientport }}
    - name: server-port
      port: {{ .Values.service.serverport }}
  selector:
    app: {{ .Values.name }}
