replicaCount: 1

name: "pm-app"

namespace: "pub-search"

labels: "pm-app"

images:
  imageServer: "login1.sandbox.g3.computing.kiae.ru/pm-server"
  imageClient: "login1.sandbox.g3.computing.kiae.ru/pm-client"

deployment:
  name: pm-app
  datasetsPath: "/data/datasets"
  modelPath: "/data/model"
  mountPath: "/data"

service:
  name: "pm-app"
  type: "LoadBalancer"
  clientport: 3000
  serverport: 5000

pvc:
  name: "search-pvc"
  accessModes: "ReadWriteOnce"
  storageClassName: "csi-rbd-sc"
